const fs = require('fs');
const path = require('path');

// Simple 16x16 favicon data in base64
// This is a blue square with "AI" text, like a simplified app icon
const faviconBase64 = `
AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBgv8AQoL/AEKC/wBCgv8AQoL/AEKC/wBCgv8AQoL/AEKC
/wBCgv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKC/wBCgv8AQoL/AEKC/wBCgv8AQoL/AEKC/wBC
gv8AQoL/AEKC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKC/wBCgv8AQoL/AEKC/wBCgv8AQoL/
AEKC/wBCgv8AQoL/AEKC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKC/wBCgv8AQoL/AKn//wCp
//8AQoL/AKn//wCp//8AQoL/AEKC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKC/wBCgv8AQoL/
AKn//wCp//8AQoL/AKn//wCp//8AQoL/AEKC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKC/wBC
gv8AQoL/AKn//wCp//8AQoL/AKn//wCp//8AQoL/AEKC/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AEKC/wBCgv8AQoL/AKn//wCp//8AQoL/AKn//wCp//8AQoL/AEKC/wAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAKT//wCp//8Aqf//AKn//wCp//8Aqf//AKn//wCp//8Aqf//AKn//wAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAKT//8Aqf//AKn//wCp//8Aqf//AKn//wCp//8Aqf//AKn//wCp//8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAKT//8Aqf//AKn//wBCgv8AQoL/AEKC/wBCgv8AQoL/AKn//wCp
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEKT//8Aqf//AKn//wBCgv8AQoL/AEKC/wBCgv8AQoL/
AKn//wCp//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKT//8Aqf//AKn//wCp//8Aqf//AKn//wCp
//8Aqf//AKn//wCp//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKT//8Aqf//AKn//wCp//8Aqf//
AKn//wCp//8Aqf//AKn//wCp//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//AAD//wAA//8AAP//
AAD//wAA//8=
`.trim();

// Write the favicon
const faviconPath = path.join(__dirname, '../public/favicon.ico');
const faviconBuffer = Buffer.from(faviconBase64, 'base64');

fs.writeFileSync(faviconPath, faviconBuffer);
console.log(`Created favicon at ${faviconPath}`); 